######################################################################
#
# File name : tb_top_hdmi_block_move_wave.do
# Created on: Fri Jul 07 11:07:44 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
