######################################################################
#
# File name : tb_top_hdmi_block_move_compile.do
# Created on: Fri Jul 07 11:07:42 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
C:\\modeltech64_10.5\\win64\\vlib modelsim_lib/work
C:\\modeltech64_10.5\\win64\\vlib modelsim_lib/msim

C:\\modeltech64_10.5\\win64\\vlib modelsim_lib/msim/xil_defaultlib

C:\\modeltech64_10.5\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

C:\\modeltech64_10.5\\win64\\vlog  -incr -work xil_defaultlib  "+incdir+../../../../hdmi_block_move.gen/sources_1/ip/clk_wiz_0" \
"../../../../hdmi_block_move.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_clk_wiz.v" \
"../../../../hdmi_block_move.gen/sources_1/ip/clk_wiz_0/clk_wiz_0.v" \
"../../../../../rtl/asyn_rst_syn.v" \
"../../../../../rtl/dvi_encoder.v" \
"../../../../../rtl/dvi_transmitter_top.v" \
"../../../../../rtl/serializer_10_to_1.v" \
"../../../../../rtl/top_hdmi_block_move.v" \
"../../../../../rtl/video_display.v" \
"../../../../../rtl/video_driver.v" \
"../../../../../sim/tb_top_hdmi_block_move.v" \


# compile glbl module
C:\\modeltech64_10.5\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

