webtalk_init -webtalk_dir C:/Users/Admin/Desktop/wang/7020/14_hdmi_block_move/prj/hdmi_block_move.sim/sim_1/behav/xsim/xsim.dir/tb_top_hdmi_block_move_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Jul  7 11:07:32 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "107de474-bcd6-4432-b37a-c8f6a0dd6988" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "4e52d9b9ca154129a047f623a8ddf8be" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 9 5900X 12-Core Processor            " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3700 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1489830766 ps" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "7" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "91.65_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "21664_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1741265143 -regid "" -xml C:/Users/Admin/Desktop/wang/7020/14_hdmi_block_move/prj/hdmi_block_move.sim/sim_1/behav/xsim/xsim.dir/tb_top_hdmi_block_move_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Admin/Desktop/wang/7020/14_hdmi_block_move/prj/hdmi_block_move.sim/sim_1/behav/xsim/xsim.dir/tb_top_hdmi_block_move_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Admin/Desktop/wang/7020/14_hdmi_block_move/prj/hdmi_block_move.sim/sim_1/behav/xsim/xsim.dir/tb_top_hdmi_block_move_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
